"""add_reviewed_text_to_feedback_reports

Revision ID: 5e9dc43fefb5
Revises: c7924d7fdba0
Create Date: 2026-05-20 23:16:52.521788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9dc43fefb5'
down_revision: Union[str, Sequence[str], None] = 'c7924d7fdba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_embedding_cosine'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat', postgresql_where='(embedding IS NOT NULL)')
    op.add_column('feedback_reports', sa.Column('reviewed_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_reports', 'reviewed_text')
    op.create_index(op.f('ix_document_chunks_embedding_cosine'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat', postgresql_where='(embedding IS NOT NULL)')
    # ### end Alembic commands ###
