"""add_source_type_to_proposed_changes

Revision ID: 6fe362967736
Revises: 1ebf40fb8611
Create Date: 2026-05-18 22:36:23.766606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe362967736'
down_revision: Union[str, Sequence[str], None] = '1ebf40fb8611'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('proposed_document_changes',
        sa.Column('source_type', sa.String(length=50), nullable=True)
    )
    op.execute("UPDATE proposed_document_changes SET source_type = 'feedback' WHERE source_type IS NULL")
    op.alter_column('proposed_document_changes', 'source_type', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposed_document_changes', 'source_type')
    # ### end Alembic commands ###
