"""add_original_file_path_to_documents

Revision ID: 71657cac9b75
Revises: 95bc67608c06
Create Date: 2026-05-20 10:09:52.901174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71657cac9b75'
down_revision: Union[str, Sequence[str], None] = '95bc67608c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_file_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'original_file_path')
    # ### end Alembic commands ###
