"""add jira tables and sr jira fields

Revision ID: 75fcdfd10b3f
Revises: c3a8f201de77
Create Date: 2026-05-18 17:15:00.669926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75fcdfd10b3f'
down_revision: Union[str, Sequence[str], None] = 'c3a8f201de77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_callback_logs',
    sa.Column('jira_issue_key', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sr_draft_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jira_configs',
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('api_token', sa.Text(), nullable=False),
    sa.Column('project_key', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trigger_status_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sr_drafts', sa.Column('jira_issue_key', sa.String(length=50), nullable=True))
    op.add_column('sr_drafts', sa.Column('jira_issue_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sr_drafts', 'jira_issue_url')
    op.drop_column('sr_drafts', 'jira_issue_key')
    op.drop_table('jira_configs')
    op.drop_table('jira_callback_logs')
    # ### end Alembic commands ###
