"""add_manual_job_id_and_nullable_fks_to_proposed_changes

Revision ID: 76eed6079966
Revises: 6fe362967736
Create Date: 2026-05-18 22:43:21.335954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76eed6079966'
down_revision: Union[str, Sequence[str], None] = '6fe362967736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposed_document_changes', sa.Column('manual_job_id', sa.UUID(), nullable=True))
    op.alter_column('proposed_document_changes', 'feedback_report_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('proposed_document_changes', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('proposed_document_changes', 'document_version_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'proposed_document_changes', 'manual_generation_jobs', ['manual_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposed_document_changes', type_='foreignkey')
    op.alter_column('proposed_document_changes', 'document_version_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('proposed_document_changes', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('proposed_document_changes', 'feedback_report_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('proposed_document_changes', 'manual_job_id')
    # ### end Alembic commands ###
