"""add target_url to sr_drafts and error_message to jira_callback_logs

Revision ID: 8db56e78aca3
Revises: 76eed6079966
Create Date: 2026-05-19 03:46:58.361171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db56e78aca3'
down_revision: Union[str, Sequence[str], None] = '76eed6079966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_callback_logs', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('sr_drafts', sa.Column('target_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sr_drafts', 'target_url')
    op.drop_column('jira_callback_logs', 'error_message')
    # ### end Alembic commands ###
