"""add view_count priority and manual_generation_jobs

Revision ID: b1373546eae4
Revises: ed059246fa15
Create Date: 2026-05-17 19:08:51.786288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1373546eae4'
down_revision: Union[str, Sequence[str], None] = 'ed059246fa15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_generation_jobs',
    sa.Column('source_sr_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.String(length=2000), nullable=False),
    sa.Column('login_id', sa.String(length=500), nullable=True),
    sa.Column('login_pw', sa.String(length=500), nullable=True),
    sa.Column('login_url', sa.String(length=2000), nullable=True),
    sa.Column('scenario_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('output_document_id', sa.UUID(), nullable=True),
    sa.Column('screenshots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['output_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['source_sr_id'], ['sr_drafts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('priority', sa.String(length=20), nullable=False, server_default='medium'))
    op.add_column('documents', sa.Column('view_count', sa.Integer(), nullable=False, server_default='0'))
    op.create_foreign_key(None, 'documents', 'document_versions', ['current_version_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'view_count')
    op.drop_column('documents', 'priority')
    op.drop_table('manual_generation_jobs')
    # ### end Alembic commands ###
