"""add source_file_url to documents

Revision ID: c43dcb6cf3ca
Revises: a1b2c3d4e5f6
Create Date: 2026-05-19 23:07:21.786041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43dcb6cf3ca'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_file_url', sa.String(length=1000), nullable=True))
    op.drop_index(op.f('ix_documents_jira_issue_key'), table_name='documents')
    op.drop_index(op.f('ix_documents_related_sr_id'), table_name='documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_related_sr_id'), 'documents', ['related_sr_id'], unique=False)
    op.create_index(op.f('ix_documents_jira_issue_key'), 'documents', ['jira_issue_key'], unique=False)
    op.drop_column('documents', 'source_file_url')
    # ### end Alembic commands ###
